spring.application.name=demo
spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/amateur_db?useSSL=true&enabledTLSProtocols=TLSv1.2&createDatabaseIfNotExist=true
spring.datasource.username=3MM2WgsfxWcY7So.root
spring.datasource.password=KsCf7aTcXrzRv6MK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hapa ndipo palikuwa na kosa (Nafasi imeondolewa sasa)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=10000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=evodiphinince@gmail.com
spring.mail.password=kbqt mpte vmuo pppv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
