spring.application.name=demo
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

# ==========================================
# UNGANISHA NA DATABASE YA MTANDAONI (TiDB CLOUD)
# ==========================================
# Tumebadilisha localhost kuwa anwani ya TiDB uliyopata
spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/sys?useSSL=true&enabledTLSProtocols=TLSv1.2
spring.datasource.username=3MM2WgsfxWcY7So.root
spring.datasource.password=wKkZUM5EaNP1hDbr

# Driver kwa ajili ya JDBC (Inabaki ile ile)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HII ITAJENGA TABLE ZAKO OTOMATIKI KWENYE TiDB
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ==========================================
# PORT KWA AJILI YA SERVER
# ==========================================
# Render mara nyingi inategemea port 8080 au 10000, 
# lakini 5023 inaweza kufanya kazi ukiset kwenye Render settings.
server.port:7272

# ==========================================
# EMAIL SETTINGS (Gmail) - Inabaki vile vile
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=evodiphinince@gmail.com
spring.mail.password=kbqt mpte vmuo pppv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.open-in-view=false
